#! /usr/bin/env python3

import sys
from ipaddress import IPv4Network

result = []

try:
    with open(sys.argv[1], 'r') as f:
        for line in f:
            if line.startswith('#') or line.startswith('S'):
                continue
            start, _, mask = line.split()[:3]

            net = IPv4Network((start, int(mask)))
            result.append(str(net))

except Exception as e:
    print(f"Exception translating file {e!r}", file=sys.stderr)
    result = ["0.0.0.0/32"]

result.sort()

print('# Generated by panwdbl-actions based on dshield top 20 block list')
print('\n'.join(result))
