#! /usr/bin/env python3

import sys
from ipaddress import (
    IPv4Network, IPv6Network,
    ip_network, collapse_addresses
)
from typing import List, Union, Any, cast

result4: List[IPv4Network] = []
result6: List[IPv6Network] = []

try:
    with open(sys.argv[1], 'r') as f:
        for line in f:
            if line.startswith('#'):
                continue

            _, net_str, _ = line.split(',',2)
            net = ip_network(net_str)

            if isinstance(net,IPv4Network):
                result4.append(net)
            elif isinstance(net,IPv6Network):
                result6.append(net)
            else:
                continue

except Exception as e:
    print(f"Exception translating file {e!r}", file=sys.stderr)
    result = [IPv4Network("0.0.0.0/32")]

result_strings = sorted([str(net) for net in collapse_addresses(result4)])
result_strings.extend(sorted([str(net) for net in collapse_addresses(result6)]))

print(f'# Generated by panwdbl-actions based on data from {sys.argv[2]}')
print('\n'.join(result_strings))
